version: '3.8'

services:
  # Cassandra node 1
  cass1:
    image: cassandra:3.11.8
    container_name: cass1
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra-data1:/var/lib/cassandra

  # Cassandra node 2
  cass2:
    image: cassandra:3.11.8
    container_name: cass2
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9043:9042"
      - "7001:7000"
    volumes:
      - cassandra-data2:/var/lib/cassandra

  # Cassandra node 3
  cass3:
    image: cassandra:3.11.8
    container_name: cass3
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9044:9042"
      - "7002:7000"
    volumes:
      - cassandra-data3:/var/lib/cassandra

  # Aplikacja skracająca URL
  url-shortener:
    build:
      context: ./url-shortener
    container_name: url-shortener
    ports:
      - "8080:8080"
    depends_on:
      - cass1
    networks:
      - cassandra

  # Aplikacja do redirectów
  url-redirector:
    build:
      context: ./url-redirector
    container_name: url-redirector
    ports:
      - "8081:8081"
    depends_on:
      - cass1
      - url-shortener
    networks:
      - cassandra

  # Serwis czyszczący stare wpisy
  url-cleaner:
    build:
      context: ./url-cleaner
    container_name: url-cleaner
    depends_on:
      - cass1
      - url-shortener
    networks:
      - cassandra

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:

networks:
  cassandra:
    driver: bridge
