version: '3.8'

services:
  cass1:
    image: cassandra:3.11.8
    container_name: cass1
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra-data1:/var/lib/cassandra

  cass2:
    image: cassandra:3.11.8
    container_name: cass2
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9043:9042"
      - "7001:7000"
    volumes:
      - cassandra-data2:/var/lib/cassandra

  cass3:
    image: cassandra:3.11.8
    container_name: cass3
    networks:
      - cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=LoggingCluster
      - CASSANDRA_SEEDS=cass1,cass2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9044:9042"
      - "7002:7000"
    volumes:
      - cassandra-data3:/var/lib/cassandra

networks:
  cassandra:
    driver: bridge

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:
