all:
  children:
    dev:
      hosts:
        dev-server:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: root
      vars:
        environment: dev
        cassandra_nodes: 1
        kafka_brokers: 1
        app_instances: 1
    
    staging:
      hosts:
        staging-server:
          ansible_host: staging.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/staging_key
      vars:
        environment: staging
        cassandra_nodes: 2
        kafka_brokers: 2
        app_instances: 1
    
    prod:
      hosts:
        prod-server-1:
          ansible_host: prod1.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
        prod-server-2:
          ansible_host: prod2.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
        prod-server-3:
          ansible_host: prod3.example.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
      vars:
        environment: production
        cassandra_nodes: 3
        kafka_brokers: 3
        app_instances: 2
    
    cassandra:
      children:
        dev: {}
        staging: {}
        prod: {}
    
    kafka:
      children:
        dev: {}
        staging: {}
        prod: {}
    
    app:
      children:
        dev: {}
        staging: {}
        prod: {} 