---
# Instalacja i konfiguracja Docker

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker (RedHat)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add application user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: yes

- name: Create Docker daemon configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root

- name: Create Docker Compose symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Configure Docker log rotation
  template:
    src: logrotate-docker.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: '0644'

- name: Create Docker networks
  docker_network:
    name: "{{ item }}"
    state: present
  loop:
    - cassandra
    - kafka
    - monitoring 