name: CI + Docker + GHCR

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/url-shortener

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean verify

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest ./url-shortener

      - name: Push image to GHCR
        run: |
          docker push $IMAGE_NAME:latest
